imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

services:
    twig.extension.text:
            class: Twig_Extensions_Extension_Text
            tags:
                - { name: twig.extension }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    bundles:
        - AppBundle
    assets:
        font-awesome-webfont-ttf:
            inputs: '@AppBundle/Resources/public/templateEvanto/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        font-awesome-webfont-woff:
            inputs: '@AppBundle/Resources/public/templateEvanto/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
        font-awesome-webfont-woff2:
            inputs: '@AppBundle/Resources/public/templateEvanto/fonts/fontawesome-webfont.woff2'
            output: 'fonts/fontawesome-webfont.woff2'
        monasterat-font:
            inputs: '@AppBundle/Resources/public/templateEvanto/fonts/montserrat-fonts.css'
            output: 'fonts/montserrat-fonts.css'
        revicons-ttf:
            inputs: '@AppBundle/Resources/public/templateEvanto/rs-plugin/font/revicons.ttf'
            output: 'font/revicons.ttf'
        revicons-woff:
            inputs: '@AppBundle/Resources/public/templateEvanto/rs-plugin/font/revicons.woff'
            output: 'font/revicons.woff'
        ionicons-ttf:
            inputs: '@AppBundle/Resources/public/templateEvanto/fonts/ionicons.ttf'
            output: 'fonts/ionicons.ttf'
        ionicons-woff:
            inputs: '@AppBundle/Resources/public/templateEvanto/fonts/ionicons.woff'
            output: 'fonts/ionicons.woff'
        animate-css:
            inputs: '@AppBundle/Resources/public/templateEvanto/css/animate.css'
            output: 'css/animate.css'

