app_textbook_main_introduction:
    path:     /{_locale}/textbook/introduction
    defaults: { _controller: AppBundle:Textbook\Main:introduction, _locale: en }
    requirements:
        _locale:  en|sk

app_textbook_logarithms_inequalities_introduction:
    path:     /{_locale}/textbook/logarithms/logarithmic-inequalities/introduction
    defaults: { _controller: AppBundle:Textbook\Logarithms:logarithmicInequalitiesIntroduction, _locale: en }
    requirements:
        _locale:  en|sk

app_textbook_logarithms_inequalities_problem1:
    path:     /{_locale}/textbook/logarithms/logarithmic-inequalities/problem-1
    defaults: { _controller: AppBundle:Textbook\Logarithms:logarithmicInequalitiesProblem1, _locale: en }
    requirements:
        _locale:  en|sk

app_textbook_logarithms_inequalities_problem1_challenge1:
    path:     /{_locale}/textbook/logarithms/logarithmic-inequalities/problem-1/challenge-1
    defaults: { _controller: AppBundle:Textbook\Logarithms:logarithmicInequalitiesProblem1Challenge1, _locale: en }
    requirements:
        _locale:  en|sk

app_textbook_logarithms_inequalities_problem1_challenge2:
    path:     /{_locale}/textbook/logarithms/logarithmic-inequalities/problem-1/challenge-2
    defaults: { _controller: AppBundle:Textbook\Logarithms:logarithmicInequalitiesProblem1Challenge2, _locale: en }
    requirements:
        _locale:  en|sk

app_textbook_logarithms_inequalities_problem1_challenge3:
    path:     /{_locale}/textbook/logarithms/logarithmic-inequalities/problem-1/challenge-3
    defaults: { _controller: AppBundle:Textbook\Logarithms:logarithmicInequalitiesProblem1Challenge3, _locale: en }
    requirements:
        _locale:  en|sk