app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_book_main_introudction:
    path:     /{_locale}/book/introduction
    defaults: { _controller: AppBundle:Book/Main:introduction, _locale: en }
    requirements:
        _locale:  en|sk

app_book_main_result:
    path:     /{_locale}/book/result
    defaults: { _controller: AppBundle:Book/Main:result, _locale: en }
    requirements:
        _locale:  en|sk

app_students_main_introudction:
    path:     /{_locale}/students/introduction
    defaults: { _controller: AppBundle:Student/Main:introduction, _locale: en }
    requirements:
        _locale:  en|sk

app_teachers_main_introudction:
    path:     /{_locale}/teachers/introduction
    defaults: { _controller: AppBundle:Teacher/Main:introduction, _locale: en }
    requirements:
        _locale:  en|sk
