app_main:
    resource: "routing/main.yml"
    prefix: /

app_book:
    resource: "routing/book.yml"
    prefix: /

app_textbook:
    resource: "routing/textBook.yml"
    prefix: /

app_students:
    resource: "routing/students.yml"
    prefix: /

app_teachers:
    resource: "routing/teachers.yml"
    prefix: /

app_researchers:
    resource: "routing/researchers.yml"
    prefix: /

app_personal:
    resource: "routing/personal.yml"
    prefix: /












