app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_book_main_introudction:
    path:     /{_locale}/book/introduction
    defaults: { _controller: AppBundle:Book/Main:introduction, _locale: en }
    requirements:
        _locale:  en|sk

app_book_main_result:
    path:     /{_locale}/book/result
    defaults: { _controller: AppBundle:Book/Main:result, _locale: en }
    requirements:
        _locale:  en|sk

app_book_main_game_instruction:
    path:     /{_locale}/book/game-instruction
    defaults: { _controller: AppBundle:Book/Main:gameInstruction, _locale: en }
    requirements:
        _locale:  en|sk

app_book_first_chapter_tasks:
    path:     /{_locale}/book/first-chapter/tasks
    defaults: { _controller: AppBundle:Book/FirstChapter:tasks, _locale: en }
    requirements:
        _locale:  en|sk

app_book_first_chapter_result:
    path:     /{_locale}/book/first-chapter/spirometry-result
    defaults: { _controller: AppBundle:Book/FirstChapter:result, _locale: en }
    requirements:
        _locale:  en|sk

app_book_first_chapter_game:
    path:     /{_locale}/book/first-chapter/game
    defaults: { _controller: AppBundle:Book/FirstChapter:game, _locale: en }
    requirements:
        _locale:  en|sk

app_book_first_chapter_game_task1:
    path:     /{_locale}/book/first-chapter/game/task1
    defaults: { _controller: AppBundle:Book/FirstChapter:gameTask1, _locale: en }
    requirements:
        _locale:  en|sk

app_book_first_chapter_game_task2:
    path:     /{_locale}/book/first-chapter/game/task2
    defaults: { _controller: AppBundle:Book/FirstChapter:gameTask2, _locale: en }
    requirements:
        _locale:  en|sk

app_book_first_chapter_game_task3:
    path:     /{_locale}/book/first-chapter/game/task3
    defaults: { _controller: AppBundle:Book/FirstChapter:gameTask3, _locale: en }
    requirements:
        _locale:  en|sk

app_book_first_chapter_game_task4:
    path:     /{_locale}/book/first-chapter/game/task4
    defaults: { _controller: AppBundle:Book/FirstChapter:gameTask4, _locale: en }
    requirements:
        _locale:  en|sk

app_book_first_chapter_history_mathematicians:
    path:     /{_locale}/book/first-chapter/history-mathematicians
    defaults: { _controller: AppBundle:Book/FirstChapter:historyMathematicians, _locale: en }
    requirements:
        _locale:  en|sk

app_students_main_introduction:
    path:     /{_locale}/students/introduction
    defaults: { _controller: AppBundle:Student/Main:introduction, _locale: en }
    requirements:
        _locale:  en|sk

app_teachers_main_introduction:
    path:     /{_locale}/teachers/introduction
    defaults: { _controller: AppBundle:Teacher/Main:introduction, _locale: en }
    requirements:
        _locale:  en|sk

app_researchers_main_resources:
    path:     /{_locale}/researchers/resources
    defaults: { _controller: AppBundle:Researcher/Main:resources, _locale: en }
    requirements:
        _locale:  en|sk

app_personal_martina_babinska:
    path:     /{_locale}/personal/babinska-martina
    defaults: { _controller: AppBundle:Personal/BabinskaMartina:introduction, _locale: en }
    requirements:
        _locale:  en|sk

