app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_book_main_introudction:
    path:     /{_locale}/book/introduction
    defaults: { _controller: AppBundle:Book/Main:introduction, _locale: en }
    requirements:
        _locale:  en|sk
